spring.application.name=InvoiceSystem

spring.mongodb.uri=mongodb://admin:Dinethmi2004@ac-pdwkcjl-shard-00-00.is2yhon.mongodb.net:27017,ac-pdwkcjl-shard-00-01.is2yhon.mongodb.net:27017,ac-pdwkcjl-shard-00-02.is2yhon.mongodb.net:27017/invoicedb?ssl=true&replicaSet=atlas-bjg715-shard-0&authSource=admin&retryWrites=true&w=majority&serverSelectionTimeoutMS=5000&connectTimeoutMS=5000
spring.mongodb.database=invoicedb
spring.data.mongodb.auto-index-creation=true

server.port=8080
spring.thymeleaf.cache=false

# Profit section password (admin-only — change this to your preferred password)
profit.password=IDEC2024